server:
  port: 7011
  servlet:
    context-path: /api
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:aries}
    password: ${MYSQL_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_HOSTNAME:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:aries}?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
