### get
GET {{hostname}}/categories/{{categoryId}}


### list
GET {{hostname}}/categories?tagId={{tagId}}


### create
POST {{hostname}}/categories
Content-Type: application/json

{
  "tagId": "{{tagId}}",
  "name": "邮箱"
}


### update
PUT {{hostname}}/categories/{{categoryId}}
Content-Type: application/json

{
  "id": "{{categoryId}}",
  "tagId": "{{tagId}}",
  "name": "搜索引擎"
}


### remove
DELETE {{hostname}}/categories/49bb9843-8985-406c-b3aa-3c73dc08312e
