### get()
GET http://{{hostname}}/api/tags/{{tagId}}

### list()
GET http://{{hostname}}/api/tags

### create()
POST http://{{hostname}}/api/tags
Content-Type: application/json

{
  "name": "娱乐"
}

### update
PUT http://{{hostname}}/api/tags/{{tagId}}
Content-Type: application/json

{
  "name": "常用"
}

### remove()
DELETE http://{{hostname}}/api/tags/02ed71c6-bf45-45cf-81a9-5b102ac86b9b
