### get
GET {{hostname}}/tags/{{tagId}}


### list
GET {{hostname}}/tags


### create
POST {{hostname}}/tags
Content-Type: application/json

{
  "name": "1024"
}


### update
PUT {{hostname}}/tags/{{tagId}}
Content-Type: application/json

{
  "id": "{{tagId}}",
  "name": "常用"
}


### remove
DELETE {{hostname}}/tags/59b201ce-01ed-48c8-a003-7d20c389039b
