---
- hosts: aries
  gather_facts: false
  remote_user: root
  vars:
    root_path: /home/nginx/kuretru.com/api
    version: 0.4.0
  tasks:
  - name: deploy
    copy: 
      src: "../../Aries-Navigation-Api/aries-navigation-api/target/aries-navigation-api-{{ version }}.jar"
      dest: "{{ root_path }}/aries-navigation-api-{{ version }}.jar"
      owner: nginx
      group: nginx
      mode: 0755
      backup: yes
  - name: restart service
    ansible.builtin.systemd: 
      state: restarted
      name: aries
