name: CI
on: [ push, pull_request ]
jobs:
  backend:
    name: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build Aries Navigation Parent
        run: mvn --batch-mode --update-snapshots install
        working-directory: Aries-Navigation-Api/
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    env:
      working-directory: Aries-Navigation-Web/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # cache: 'yarn'
          # cache-dependency-path: 'Aries-Navigation-Web/yarn.lock'
      - name: Dependency
        # run: yarn install --immutable
        run: yarn install
        working-directory: ${{env.working-directory}}
      # - name: Lint
      #   run: yarn lint
      #   working-directory: ${{env.working-directory}}
      # - name: Test
      #   run: yarn test
      #   working-directory: ${{env.working-directory}}
      - name: Build
        run: yarn build
        working-directory: ${{env.working-directory}}
